/** Università in evidenza sulla homepage */
export const POPULAR_UNIVERSITIES = [
  "Sapienza — Roma",
  "Università Statale — Milano",
  "Politecnico — Milano",
  "Università di Bologna",
  "Università di Padova",
  "Federico II — Napoli",
  "Università di Torino",
  "Università di Firenze",
  "Università di Pisa",
  "Bocconi — Milano",
  "Università di Trento",
  "Università Cattolica — Milano",
  "Università di Bari",
  "Università di Palermo",
  "Università di Catania",
  "Politecnico — Torino",
] as const;

/** Elenco esteso per suggerimenti in upload e ricerca */
export const ITALIAN_UNIVERSITIES = [
  "Bocconi — Milano",
  "Federico II — Napoli",
  "IULM — Milano",
  "Libera Università di Bolzano",
  "LUISS — Roma",
  "Politecnico — Bari",
  "Politecnico — Milano",
  "Politecnico — Torino",
  "Sant'Anna — Pisa",
  "Sapienza — Roma",
  "Scuola Normale Superiore — Pisa",
  "Università Ca' Foscari — Venezia",
  "Università Cattolica — Milano",
  "Università del Piemonte Orientale",
  "Università del Salento — Lecce",
  "Università della Calabria",
  "Università della Tuscia — Viterbo",
  "Università di Ancona (Politecnica delle Marche)",
  "Università di Bari",
  "Università di Bergamo",
  "Università di Bologna",
  "Università di Brescia",
  "Università di Cagliari",
  "Università di Camerino",
  "Università di Cassino e del Lazio Meridionale",
  "Università di Catania",
  "Università di Chieti-Pescara (G. d'Annunzio)",
  "Università di Enna Kore",
  "Università di Ferrara",
  "Università di Firenze",
  "Università di Foggia",
  "Università di Genova",
  "Università di Insubria",
  "Università di L'Aquila",
  "Università di Macerata",
  "Università di Messina",
  "Università di Milano-Bicocca",
  "Università di Modena e Reggio Emilia",
  "Università di Napoli L'Orientale",
  "Università di Napoli Parthenope",
  "Università di Padova",
  "Università di Palermo",
  "Università di Parma",
  "Università di Pavia",
  "Università di Perugia",
  "Università di Pisa",
  "Università di Reggio Calabria",
  "Università di Roma Tre",
  "Università di Salerno",
  "Università di Sassari",
  "Università di Siena",
  "Università di Teramo",
  "Università di Torino",
  "Università di Tor Vergata — Roma",
  "Università di Trento",
  "Università di Trieste",
  "Università di Udine",
  "Università di Urbino Carlo Bo",
  "Università di Verona",
  "Università IUAV — Venezia",
  "Università LUMSA — Roma",
  "Università Statale — Milano",
  "Università della Campania Luigi Vanvitelli",
  "Università Internazionale UNINT — Roma",
  "Università Link Campus — Roma",
  "Università Suor Orsola Benincasa — Napoli",
  "Università Europea di Roma",
  "Università Vita-Salute San Raffaele — Milano",
  "Università Campus Bio-Medico — Roma",
  "Università degli Studi del Sannio — Benevento",
  "Università degli Studi della Basilicata — Potenza",
  "Università degli Studi di Fisciano (SA)",
] as const;

/** Lista unica ordinata alfabeticamente (per datalist) */
export const ALL_UNIVERSITIES = [
  ...new Set([...POPULAR_UNIVERSITIES, ...ITALIAN_UNIVERSITIES]),
].sort((a, b) => a.localeCompare(b, "it"));

export const SITE_NAME = "Stufy";

/** Incrementa quando cambi images/logo1.png (evita cache browser/Next) */
export const LOGO_VERSION = "7";
